[tool.commitizen]
name = "cz_conventional_commits"
version = "0.4.21"
tag_format = "$version"
version_files = [
    "naas/__init__.py",
    "naas/runner/runner.py",
    ".cz.toml",
    "setup.py:version",
    "Dockerfile"
]