[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$minor.$major.$patch$prerelease"
version = "0.5.26"
version_files = [
    "naas/__init__.py",
    "naas/runner/runner.py",
    ".cz.toml",
    "setup.py:version",
    "Dockerfile"
]
