name: Build Docker Image

on:
  repository_dispatch:
    types: [pypip-deployed]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy image on Dockerhub"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
      - run: echo ${{ github.event.client_payload.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: get_version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - name: Get smart tag
        id: prepare
        uses: jupyter-naas/docker-smart-tag-action@1.0.0
        with:
          ref: ${{ github.event.client_payload.ref }}
          docker_image: jupyternaas/naas
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
      # - name: Push to GitHub Packages
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: docker.pkg.github.com
      #     repository: naas
      #     tags: ${{ steps.prepare.outputs.tag }}
      - name: Image digest
        run: echo ${{ steps.prepare.outputs.tag }}
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Naas # Optional. (defaults to webhook app)
          SLACK_CHANNEL: naas-ci # Optional. (defaults to webhook)
          SLACK_AVATAR: repository
          SLACK_CUSTOM_PAYLOAD: '{"attachments":[{"color":"#47dd82","blocks":[{"type":"section","block_id":"section567","text":{"type":"mrkdwn","text":"<https://github.com/jupyter-naas/naas|Naas> \n Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."},"accessory":{"type":"image","image_url":"https://github.com/jupyter-naas/naas/raw/main/custom/naas-fav.png","alt_text":"Naas logo"}},{"type":"section","block_id":"section789","fields":[{"type":"mrkdwn","text":"*Average Rating*\n${{ github.event.client_payload.ref }}"}]}]}]}'
        uses: Ilshidur/action-slack@2.0.2
