name: Upload Python Package

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install
        python3 setup.py sdist
    - name: Deploy Pypi
      uses: remorses/pypi@v3
      with:
        username: ${{ secrets.PYPIP_USERNAME }} 
        password: ${{ secrets.PYPIP_PASSWORD }}
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jupyternaas/naas:${{ steps.vars.outputs.tag }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
